# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class HeartRateTrip(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, time: datetime=None, heartrate: float=None):  # noqa: E501
        """HeartRateTrip - a model defined in Swagger

        :param time: The time of this HeartRateTrip.  # noqa: E501
        :type time: datetime
        :param heartrate: The heartrate of this HeartRateTrip.  # noqa: E501
        :type heartrate: float
        """
        self.swagger_types = {
            'time': datetime,
            'heartrate': float
        }

        self.attribute_map = {
            'time': 'time',
            'heartrate': 'heartrate'
        }
        self._time = time
        self._heartrate = heartrate

    @classmethod
    def from_dict(cls, dikt) -> 'HeartRateTrip':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_3 of this HeartRateTrip.  # noqa: E501
        :rtype: HeartRateTrip
        """
        return util.deserialize_model(dikt, cls)

    @property
    def time(self) -> datetime:
        """Gets the time of this HeartRateTrip.


        :return: The time of this HeartRateTrip.
        :rtype: datetime
        """
        return self._time

    @time.setter
    def time(self, time: datetime):
        """Sets the time of this HeartRateTrip.


        :param time: The time of this HeartRateTrip.
        :type time: datetime
        """

        self._time = time

    @property
    def heartrate(self) -> float:
        """Gets the heartrate of this HeartRateTrip.


        :return: The heartrate of this HeartRateTrip.
        :rtype: float
        """
        return self._heartrate

    @heartrate.setter
    def heartrate(self, heartrate: float):
        """Sets the heartrate of this HeartRateTrip.


        :param heartrate: The heartrate of this HeartRateTrip.
        :type heartrate: float
        """

        self._heartrate = heartrate
