# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, heartrate: float=None, ratio: float=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param heartrate: The heartrate of this InlineResponse2001.  # noqa: E501
        :type heartrate: float
        :param ratio: The ratio of this InlineResponse2001.  # noqa: E501
        :type ratio: float
        """
        self.swagger_types = {
            'heartrate': float,
            'ratio': float
        }

        self.attribute_map = {
            'heartrate': 'heartrate',
            'ratio': 'ratio'
        }
        self._heartrate = heartrate
        self._ratio = ratio

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def heartrate(self) -> float:
        """Gets the heartrate of this InlineResponse2001.


        :return: The heartrate of this InlineResponse2001.
        :rtype: float
        """
        return self._heartrate

    @heartrate.setter
    def heartrate(self, heartrate: float):
        """Sets the heartrate of this InlineResponse2001.


        :param heartrate: The heartrate of this InlineResponse2001.
        :type heartrate: float
        """

        self._heartrate = heartrate

    @property
    def ratio(self) -> float:
        """Gets the ratio of this InlineResponse2001.

        Ratio of current speed to free-flow speed  # noqa: E501

        :return: The ratio of this InlineResponse2001.
        :rtype: float
        """
        return self._ratio

    @ratio.setter
    def ratio(self, ratio: float):
        """Sets the ratio of this InlineResponse2001.

        Ratio of current speed to free-flow speed  # noqa: E501

        :param ratio: The ratio of this InlineResponse2001.
        :type ratio: float
        """

        self._ratio = ratio
