# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class NumberOfTrip(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, number_of_trip: float=None):  # noqa: E501
        """InlineResponse2005 - a model defined in Swagger

        :param number_of_trip: The number_of_trip of this InlineResponse2005.  # noqa: E501
        :type number_of_trip: float
        """
        self.swagger_types = {
            'number_of_trip': float
        }

        self.attribute_map = {
            'number_of_trip': 'number_of_trip'
        }
        self._number_of_trip = number_of_trip

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2005':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_5 of this InlineResponse2005.  # noqa: E501
        :rtype: InlineResponse2005
        """
        return util.deserialize_model(dikt, cls)

    @property
    def number_of_trip(self) -> float:
        """Gets the number_of_trip of this InlineResponse2005.


        :return: The number_of_trip of this InlineResponse2005.
        :rtype: float
        """
        return self._number_of_trip

    @number_of_trip.setter
    def number_of_trip(self, number_of_trip: float):
        """Sets the number_of_trip of this InlineResponse2005.


        :param number_of_trip: The number_of_trip of this InlineResponse2005.
        :type number_of_trip: float
        """

        self._number_of_trip = number_of_trip
